### ISSUE TITLE
CORS use case support

### ISSUE THREAD

**Issue by deathemperor** [seratch/slack-web-api-client#1]
Hello @seratch,

Original discussion started here https://github.com/slackapi/node-slack-sdk/issues/1603 (I was [papaya-reader](https://github.com/papaya-reader), mistakenly using company account)

I understand the risk allowing OAuth token in Client. My use-case isn't Electron but an internal web app. I had to compromise the risk to increase flexibility in usage on the sdk for now until there's a better way which I'm eager to listen from you. It's a concern usage of any sdk anyways.

As you may have guessed, I'm still using the sdk by patching the code

```patch
diff --git a/node_modules/slack-web-api-client/dist/client/api-client.js b/node_modules/slack-web-api-client/dist/client/api-client.js
index 259c73f..84086f9 100644
--- a/node_modules/slack-web-api-client/dist/client/api-client.js
+++ b/node_modules/slack-web-api-client/dist/client/api-client.js
@@ -401,7 +401,7 @@ class SlackAPIClient {
         const _params = {};
         Object.assign(_params, params);
         if (_params && _params.token) {
-            delete _params.token;
+            // delete _params.token;
         }
         for (const [key, value] of Object.entries(_params)) {
             if (typeof value === "object") {
@@ -423,7 +423,7 @@ class SlackAPIClient {
         }
         const response = await fetch(url, {
             method: "POST",
-            headers,
+            // headers,
             body,
         });
         const responseBody = await response.json();

```

**Comment by seratch** [comment]
Hi @deathemperor, thanks for writing in. So, your main point here is whether this API client should allow CORS use case, right? If that's the case, I still hesitate to unlock such even with this personal project. Slack's OAuth tokens must be used on the server-side. You should be able to have a proxy endpoint with authentication to ask your app's server to perform chat.postMessage etc. If you go with your patched version of this SDK on your own risks, please go ahead with it.
