### ISSUE TITLE
Missing argument for conversations.open

### ISSUE THREAD

**Issue by rd79** [seratch/slack-web-api-client#14]
Line 831 of [requests.ts](https://github.com/seratch/slack-web-api-client/blob/main/src_deno/client/request.ts):
```
export interface ConversationsOpenRequest extends SlackAPIRequest {
  channel?: string;
  users?: string; // comma-separated list of users
  return_im?: boolean;
}
```
[converstations.open](https://api.slack.com/methods/conversations.open) has a [prevent_creation](https://api.slack.com/methods/conversations.open#arg_prevent_creation) argument as well. Is there a workaround? This way it sometimes opens a new DM instead of finding an existing one. Thanks!

**Comment by seratch** [comment]
Thanks for reporting this. If you're happy to send a PR resolving this, it'd be greatly appreciated
