### ISSUE TITLE
Outdated/Incorrect Typescript Types

### ISSUE THREAD

**Issue by themashcodee** [seratch/slack-web-api-client#15]
**1. RichTextSectionChannel has wrong style**
**Line** - 425 (`export interface RichTextSectionChannel extends RichTextSectionElement {`)
**File** - `src/block-kit/block-elements.ts`
**Problem** - `RichTextSectionElementStyle` only have `bold`, `italic` and `strike`. But in real slack docs 
we have `bold`, `italic`, `strike`, `highlight`, `client_highlight`, and `unlink`.
**Docs Ref** - https://api.slack.com/reference/block-kit/blocks#element-types

**2. RichTextSectionEmoji has extra types**
**Line** - 433 (`export interface RichTextSectionEmoji extends RichTextSectionElement {`)
**File** - `src/block-kit/block-elements.ts`
**Problem** -  Real slack docs do not have `skin_tone`  and `unicode`
**Docs Ref** - https://api.slack.com/reference/block-kit/blocks#element-types

**3. Type missing in RichTextSectionLink**
**Line** - 439 (`export interface RichTextSectionLink extends RichTextSectionElement {`)
**File** - `src/block-kit/block-elements.ts`
**Problem** - `unsafe` type is missing which is specified in the real slack docs
**Docs Ref** - https://api.slack.com/reference/block-kit/blocks#element-types

**4. RichTextSectionUser has wrong style**
**Line** - 429 (`export interface RichTextSectionUser extends RichTextSectionElement {`)
**File** - `src/block-kit/block-elements.ts`
**Problem** - `RichTextSectionElementStyle` only have `bold`, `italic` and `strike`. But in real slack docs 
we have `bold`, `italic`, `strike`, `highlight`, `client_highlight`, and `unlink`.
**Docs Ref** - https://api.slack.com/reference/block-kit/blocks#element-types

**5. RichTextSectionUsergroup has wrong style**
**Line** - 449 (`export interface RichTextSectionUsergroup extends RichTextSectionElement {`)
**File** - `src/block-kit/block-elements.ts`
**Problem** - `RichTextSectionElementStyle` only have `bold`, `italic` and `strike`. But in real slack docs 
we have `bold`, `italic`, `strike`, `highlight`, `client_highlight`, and `unlink`.
**Docs Ref** - https://api.slack.com/reference/block-kit/blocks#element-types

**6. Invalid RichTextBlockSubElement type**
**Line** - 358
**File** - `src/block-kit/block-elements.ts`
**Problem** - Putting real blocks data causing error [shown in the picture below]
**Solution** - [shown in the picture below]
<img width="1440" alt="problem" src="https://github.com/seratch/slack-web-api-client/assets/50915748/78d0d338-cb30-4e3e-af27-be9f2b4415d7">
<img width="1440" alt="solution" src="https://github.com/seratch/slack-web-api-client/assets/50915748/452269cc-9815-45aa-9f2c-2de7d0fb885f">

**7. Incorrect RichTextSection, RichTextQuote and RichTextPreformatted elements type**
**description** - According to the real slack docs `rich_text_section`,`rich_text_preformatted` and `rich_text_quote` only supports `channel`, `emoji`, `link`, `text`, `user` and `usergroup`.
**docs ref** - https://api.slack.com/reference/block-kit/blocks#rich_text_section

**Comment by seratch** [comment]
Thanks for reporting these issues. Since the properties for these block types have been added over time, some of the code in this repo may miss them. I'd like to avoid reviewing a big PR with a large amount of changes, but if you're happy to send PRs for each issue, it'd be greatly appreciated. Otherwise, I will check these issues when I have time for it.

**Comment by seratch** [comment]
Thanks again for taking the time to report these issues. I just sent #16 to resolve the issues I've confirmed. For the rest,

>2. Problem - Real slack docs do not have skin_tone and unicode

These are not mentioned in the documents but they do exist. The official documents can be improved.

>6.

It seems the pattern is no longer supported? Block Kit Builder (BKB) also says it's wrong. If there are patterns working on BKB, I am happy to support the patterns.

>7.

The document lists the available ones but it does not say "only" those. The current typing should be fine.

**Comment by themashcodee** [comment]
Thanks for replying and addressing these issues.

6. Here is how you can reproduce it
- Blocks are supported on BKB - [link](https://app.slack.com/block-kit-builder/T0385D58J4Q#%7B%22blocks%22:%5B%7B%22type%22:%22rich_text%22,%22elements%22:%5B%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22This%20is%20my%20friend%20%22%7D,%7B%22type%22:%22user%22,%22user_id%22:%22U060JP64TQF%22%7D,%7B%22type%22:%22text%22,%22text%22:%22.%22%7D%5D%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22This%20is%20a%20rich%20text%20section%20with%20regular%20text.%20%22%7D,%7B%22type%22:%22text%22,%22text%22:%22This%20is%20bold%22,%22style%22:%7B%22bold%22:true%7D%7D,%7B%22type%22:%22text%22,%22text%22:%22.%20%22%7D,%7B%22type%22:%22text%22,%22text%22:%22This%20is%20italics.%22,%22style%22:%7B%22italic%22:true%7D%7D,%7B%22type%22:%22text%22,%22text%22:%22%20%22,%22style%22:%7B%22bold%22:true,%22italic%22:true%7D%7D,%7B%22type%22:%22text%22,%22text%22:%22This%20is%20strikethrough.%22,%22style%22:%7B%22strike%22:true%7D%7D,%7B%22type%22:%22text%22,%22text%22:%22%20%22%7D,%7B%22type%22:%22text%22,%22text%22:%22This%20is%20code.%22,%22style%22:%7B%22code%22:true%7D%7D,%7B%22type%22:%22text%22,%22text%22:%22%5Cn%5Cn%22%7D%5D%7D,%7B%22type%22:%22rich_text_list%22,%22elements%22:%5B%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22This%20is%20an%22%7D%5D%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22ordered%22%7D%5D%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22list%22%7D%5D%7D%5D,%22style%22:%22ordered%22,%22indent%22:0,%22border%22:0%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22%5Cn%22%7D%5D%7D,%7B%22type%22:%22rich_text_list%22,%22elements%22:%5B%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22This%20is%20an%22%7D%5D%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22unordered%22%7D%5D%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22list%22%7D%5D%7D%5D,%22style%22:%22bullet%22,%22indent%22:0,%22border%22:0%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22%5Cn%22%7D%5D%7D,%7B%22type%22:%22rich_text_quote%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22This%20is%20a%20%5Cntext%20quote%22%7D%5D%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22%5Cn%22%7D%5D%7D,%7B%22type%22:%22rich_text_preformatted%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22This%20is%20a%5Cnmulti-line%20%5Cncode%20block%22%7D%5D,%22border%22:0%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22%5CnThis%20is%20a%20%22%7D,%7B%22type%22:%22link%22,%22url%22:%22https://www.google.com/%22,%22text%22:%22link%22%7D,%7B%22type%22:%22text%22,%22text%22:%22%20to%20google.%5Cn%5Cn%22%7D%5D%7D,%7B%22type%22:%22rich_text_list%22,%22elements%22:%5B%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22We%20should%20also%20support%20nested%20styling%20like%20this%20bolded%20text%22,%22style%22:%7B%22bold%22:true%7D%7D%5D%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22in%20an%20unordered%20list%22,%22style%22:%7B%22bold%22:true%7D%7D%5D%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22on%20a%20text%20quote.%22,%22style%22:%7B%22bold%22:true%7D%7D%5D%7D%5D,%22style%22:%22bullet%22,%22indent%22:0,%22border%22:1%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22Or%20this%20%22%7D,%7B%22type%22:%22text%22,%22text%22:%22bolded%22,%22style%22:%7B%22bold%22:true,%22code%22:true%7D%7D,%7B%22type%22:%22text%22,%22text%22:%22%20code%22,%22style%22:%7B%22code%22:true%7D%7D,%7B%22type%22:%22text%22,%22text%22:%22.%5Cn%5Cn%5Cn%5CnAnd%20preserve%20whitespace/newlines?%22%7D%5D%7D%5D%7D%5D%7D)

- create a test.ts inside the block-kit folder
- paste these two code snippets to see the type error (make sure you have eslint enabled)

#1 Code Snippet
```
import {
  AnyRichTextBlockElement,
  RichTextBlockSubElement,
} from "./block-elements";

export const elements: AnyRichTextBlockElement[] = [
  {
    type: "rich_text_section",
    elements: [
      {
        type: "text",
        text: "This is my friend ",
      },
      {
        type: "user",
        user_id: "U060JP64TQF",
      },
      {
        type: "text",
        text: ".",
      },
    ],
  },
  {
    type: "rich_text_section",
    elements: [
      {
        type: "text",
        text: "This is a rich text section with regular text. ",
      },
      {
        type: "text",
        text: "This is bold",
        style: {
          bold: true,
        },
      },
      {
        type: "text",
        text: ". ",
      },
      {
        type: "text",
        text: "This is italics.",
        style: {
          italic: true,
        },
      },
      {
        type: "text",
        text: " ",
        style: {
          bold: true,
          italic: true,
        },
      },
      {
        type: "text",
        text: "This is strikethrough.",
        style: {
          strike: true,
        },
      },
      {
        type: "text",
        text: " ",
      },
      {
        type: "text",
        text: "This is code.",
        style: {
          code: true,
        },
      },
      {
        type: "text",
        text: "\n\n",
      },
    ],
  },
  {
    type: "rich_text_list",
    elements: [
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "This is an",
          },
        ],
      },
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "ordered",
          },
        ],
      },
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "list",
          },
        ],
      },
    ],
    style: "ordered",
    indent: 0,
    border: 0,
  },
  {
    type: "rich_text_section",
    elements: [
      {
        type: "text",
        text: "\n",
      },
    ],
  },
  {
    type: "rich_text_list",
    elements: [
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "This is an",
          },
        ],
      },
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "unordered",
          },
        ],
      },
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "list",
          },
        ],
      },
    ],
    style: "bullet",
    indent: 0,
    border: 0,
  },
  {
    type: "rich_text_section",
    elements: [
      {
        type: "text",
        text: "\n",
      },
    ],
  },
  {
    type: "rich_text_quote",
    elements: [
      {
        type: "text",
        text: "This is a \ntext quote",
      },
    ],
  },
  {
    type: "rich_text_section",
    elements: [
      {
        type: "text",
        text: "\n",
      },
    ],
  },
  {
    type: "rich_text_preformatted",
    elements: [
      {
        type: "text",
        text: "This is a\nmulti-line \ncode block",
      },
    ],
    border: 0,
  },
  {
    type: "rich_text_section",
    elements: [
      {
        type: "text",
        text: "\nThis is a ",
      },
      {
        type: "link",
        url: "https://www.google.com/",
        text: "link",
      },
      {
        type: "text",
        text: " to google.\n\n",
      },
    ],
  },
  {
    type: "rich_text_list",
    elements: [
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "We should also support nested styling like this bolded text",
            style: {
              bold: true,
            },
          },
        ],
      },
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "in an unordered list",
            style: {
              bold: true,
            },
          },
        ],
      },
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "on a text quote.",
            style: {
              bold: true,
            },
          },
        ],
      },
    ],
    style: "bullet",
    indent: 0,
    border: 1,
  },
  {
    type: "rich_text_section",
    elements: [
      {
        type: "text",
        text: "Or this ",
      },
      {
        type: "text",
        text: "bolded",
        style: {
          bold: true,
          code: true,
        },
      },
      {
        type: "text",
        text: " code",
        style: {
          code: true,
        },
      },
      {
        type: "text",
        text: ".\n\n\n\nAnd preserve whitespace/newlines?",
      },
    ],
  },
];
```

#2 Code Snippet
```
import {
  AnyRichTextBlockElement,
  RichTextBlockSubElement,
} from "./block-elements";

export const elements: RichTextBlockSubElement[] = [
  {
    type: "rich_text_section",
    elements: [
      {
        type: "text",
        text: "This is my friend ",
      },
      {
        type: "user",
        user_id: "U060JP64TQF",
      },
      {
        type: "text",
        text: ".",
      },
    ],
  },
  {
    type: "rich_text_section",
    elements: [
      {
        type: "text",
        text: "This is a rich text section with regular text. ",
      },
      {
        type: "text",
        text: "This is bold",
        style: {
          bold: true,
        },
      },
      {
        type: "text",
        text: ". ",
      },
      {
        type: "text",
        text: "This is italics.",
        style: {
          italic: true,
        },
      },
      {
        type: "text",
        text: " ",
        style: {
          bold: true,
          italic: true,
        },
      },
      {
        type: "text",
        text: "This is strikethrough.",
        style: {
          strike: true,
        },
      },
      {
        type: "text",
        text: " ",
      },
      {
        type: "text",
        text: "This is code.",
        style: {
          code: true,
        },
      },
      {
        type: "text",
        text: "\n\n",
      },
    ],
  },
  {
    type: "rich_text_list",
    elements: [
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "This is an",
          },
        ],
      },
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "ordered",
          },
        ],
      },
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "list",
          },
        ],
      },
    ],
    style: "ordered",
    indent: 0,
    border: 0,
  },
  {
    type: "rich_text_section",
    elements: [
      {
        type: "text",
        text: "\n",
      },
    ],
  },
  {
    type: "rich_text_list",
    elements: [
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "This is an",
          },
        ],
      },
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "unordered",
          },
        ],
      },
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "list",
          },
        ],
      },
    ],
    style: "bullet",
    indent: 0,
    border: 0,
  },
  {
    type: "rich_text_section",
    elements: [
      {
        type: "text",
        text: "\n",
      },
    ],
  },
  {
    type: "rich_text_quote",
    elements: [
      {
        type: "text",
        text: "This is a \ntext quote",
      },
    ],
  },
  {
    type: "rich_text_section",
    elements: [
      {
        type: "text",
        text: "\n",
      },
    ],
  },
  {
    type: "rich_text_preformatted",
    elements: [
      {
        type: "text",
        text: "This is a\nmulti-line \ncode block",
      },
    ],
    border: 0,
  },
  {
    type: "rich_text_section",
    elements: [
      {
        type: "text",
        text: "\nThis is a ",
      },
      {
        type: "link",
        url: "https://www.google.com/",
        text: "link",
      },
      {
        type: "text",
        text: " to google.\n\n",
      },
    ],
  },
  {
    type: "rich_text_list",
    elements: [
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "We should also support nested styling like this bolded text",
            style: {
              bold: true,
            },
          },
        ],
      },
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "in an unordered list",
            style: {
              bold: true,
            },
          },
        ],
      },
      {
        type: "rich_text_section",
        elements: [
          {
            type: "text",
            text: "on a text quote.",
            style: {
              bold: true,
            },
          },
        ],
      },
    ],
    style: "bullet",
    indent: 0,
    border: 1,
  },
  {
    type: "rich_text_section",
    elements: [
      {
        type: "text",
        text: "Or this ",
      },
      {
        type: "text",
        text: "bolded",
        style: {
          bold: true,
          code: true,
        },
      },
      {
        type: "text",
        text: " code",
        style: {
          code: true,
        },
      },
      {
        type: "text",
        text: ".\n\n\n\nAnd preserve whitespace/newlines?",
      },
    ],
  },
];
```

<img width="1440" alt="Screenshot 2024-06-20 at 12 26 47 PM" src="https://github.com/seratch/slack-web-api-client/assets/50915748/8f5ac9ce-4203-416a-88df-e508e4ba4f9d">
<img width="1440" alt="Screenshot 2024-06-20 at 12 27 02 PM" src="https://github.com/seratch/slack-web-api-client/assets/50915748/7b74befa-0032-4ff7-b536-ffb968ccefc2">

**Comment by seratch** [comment]
Thanks for sharing these. Fixing the issue now.

**Comment by seratch** [comment]
version 0.13.1 should resolve the issue. Thanks again for reporting the issues!
