### ISSUE TITLE
v0.13 is breaking Slack blocks

### ISSUE THREAD

**Issue by StephenTangCook** [seratch/slack-web-api-client#18]
Hey Kaz,

Something in the v0.13.x version starting breaking our Slack app. We upgraded from v0.12.0. The chat-related API calls are failing with:

```
Error: Failed to call chat.postMessage due to invalid_blocks_format: {"ok":false,"error":"invalid_blocks_format","headers":{}}
```

Note we're also consuming `slack-cloudflare-workers` v0.13.x, but we think the change is here. I'm not entirely sure what this change is doing, but it's on my suspect list: https://github.com/seratch/slack-web-api-client/commit/c0faad561a5537d0d00fcaa384b37bb2cf0a05b8#diff-7a5692969366fd760c15fe89206e00b216e97b5e2bbd02070800417a24fde0f6R557-R561

Let me know if I can provide further details.

**Comment by seratch** [comment]
Ah yes, I am sorry about this. Could you try 0.13.3? The issue should be resolved.

**Comment by seratch** [comment]
As mentioned above, the issue has been resolved by this commit: https://github.com/seratch/slack-web-api-client/commit/7b26c29c66a63d10b9bf7f48e5d326f73f19086b

Sorry about the bug again; I've added unit tests for the pattern, thus the same one never comes in the future.
