### ISSUE TITLE
delete_original as sole attribute of respond

### ISSUE THREAD

**Issue by zhawtof** [seratch/slack-web-api-client#23]
According to these [Slack docs](https://api.slack.com/interactivity/handling#deleting_message_response), delete_original has to be sent as the sole attribute.

https://github.com/seratch/slack-web-api-client/blob/e25971057cdc429fbbab50e2070b73c7ef0752d7/src/client/webhook-client.ts#L34-L44

should now be

```ts
export type WebhookParams =
    | {
        response_type?: "ephemeral" | "in_channel";
        text: string;
        blocks?: AnyMessageBlock[];
        attachments?: MessageAttachment[];
        metadata?: MessageMetadata;
        replace_original?: boolean;
        unfurl_links?: boolean;
        unfurl_media?: boolean;
    }
    | {
        delete_original: true;
    };
```

**Comment by seratch** [comment]
yes, you're correct.

**Comment by seratch** [comment]
@zhawtof Thank you so much for reporting these issues! The latest version I just released resolves them!
