### ISSUE TITLE
Missing thread_ts in Webhook params

### ISSUE THREAD

**Issue by zhawtof** [seratch/slack-web-api-client#24]
https://github.com/seratch/slack-web-api-client/blob/e25971057cdc429fbbab50e2070b73c7ef0752d7/src/client/webhook-client.ts#L34-L44

Missing `thread_ts`

https://api.slack.com/interactivity/handling#publishing_in_thread

**Comment by seratch** [comment]
Thanks, this property didn't exist before. It need to be added

**Comment by zhawtof** [comment]
It would be nice if all of the other message properties were added, like `author username,` etc.

That change would make this so much more powerful

**Comment by seratch** [comment]
For feature addition requests, sending customer feedback via `/feedback` (with a customer account) is the best way to go. Your understanding of this process is much appreciated.

**Comment by seratch** [comment]
This is resolved by v1.0.5. I won't release slack-edge and slack-cloudflare-workers today, but you can run `npm i slack-web-api-client@latest` to upgrade this library for now. slack-edge doesn't block the upgrade.

**Comment by zhawtof** [comment]
I don't need it today, but I saw this while exploring capabilities and wanted to make sure I tagged it for you.
