### ISSUE TITLE
MrkdwnOption.description / PlainTextOption.description types don't support markdown text for checkboxes

### ISSUE THREAD

**Issue by StephenTangCook** [seratch/slack-web-api-client#6]
To preface, this might be a combination of the [API docs](https://api.slack.com/reference/block-kit/composition-objects#option) being incorrect/incomplete... or checkboxes being a special exception?

In the Block Builder, when I add the Section > checkboxes, the example data has option descriptions as `mrkdwn` ([example](https://app.slack.com/block-kit-builder/T01NWNWNR8V#%7B%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Checkboxes%22,%22emoji%22:true%7D,%22submit%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Submit%22,%22emoji%22:true%7D,%22type%22:%22modal%22,%22close%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Cancel%22,%22emoji%22:true%7D,%22blocks%22:%5B%7B%22type%22:%22actions%22,%22elements%22:%5B%7B%22type%22:%22checkboxes%22,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22description%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22value%22:%22value-0%22%7D%5D,%22action_id%22:%22actionId-0%22%7D,%7B%22type%22:%22checkboxes%22,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*this%20is%20mrkdwn%20text*%22%7D,%22description%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*this%20is%20mrkdwn%20text*%22%7D,%22value%22:%22value-0%22%7D%5D,%22action_id%22:%22actionId-1%22%7D%5D%7D%5D%7D)):
```
"options": [
  {
  "text": {
	  "type": "mrkdwn",
	  "text": "*this is mrkdwn text*"
  },
  "description": {
	  "type": "mrkdwn",
	  "text": "*this is mrkdwn text*"
  },
  "value": "value-0"
  }
]
```

I'm not sure if this applies to any other input types with options, but it looks like it is at _least_ not allowed on static select options.

Typing in question: https://github.com/seratch/slack-web-api-client/blob/0e341640e8616edca5fe82208c85df62eba06772/src/block-kit/options.ts#L7

**Comment by seratch** [comment]
Hi @StephenTangCook , thanks for sharing this. It seems that you're right on checkboxes. I just quickly checked other types but all others do not allow mrkdwn type for description.

I am fine to adjust the types in this library, but could you submit the same inquiry about the documents at https://github.com/slackapi/node-slack-sdk instead? Other team members can check the issue during North American timezone.

**Comment by StephenTangCook** [comment]
Done! https://github.com/slackapi/node-slack-sdk/issues/1765
